modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "${issue_tracker}"
license = "${license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
displayURL = "${website}"
logoFile = "vivecraft_icon.png"
authors = "${mod_authors}"
displayTest = "IGNORE_SERVER_VERSION"
description = '''
${description}

Support us on Ko-Fi: ${kofi}

Discord: ${discord}
'''
updateJSONURL = "https://raw.githubusercontent.com/Vivecraft/VivecraftMod/forge-versions/forge_updates.json"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "${forge_loader_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${forge_mc_range}"
ordering = "NONE"
side = "BOTH"
