pluginManagement {
    repositories {
        maven { url "https://maven.fabricmc.net/" }
        maven { url "https://maven.architectury.dev/" }
        maven { url "https://maven.minecraftforge.net/" }
        maven { url "https://maven.neoforged.net/" }
        gradlePluginPortal()
    }
}

Properties properties = new Properties()
File file = new File(rootProject.getProjectDir(), "local.properties")
if (file.exists())
    properties.load(new FileReader(file))

include("common")
include("stubs")
if (!"true".equals(properties.getProperty("project.build.excludeFabric")))
    include("fabric")
if (!"true".equals(properties.getProperty("project.build.excludeForge")))
    include("forge")
if (!"true".equals(properties.getProperty("project.build.excludeNeoforge")))
    include("neoforge")

rootProject.name = "vivecraft"
