plugins {
    id "com.github.johnrengelman.shadow" version "7.1.2"
}

def mixins = [
    "vivecraft.mixins.json",
    "vivecraft.forge.mixins.json",

    "vivecraft.accessories.mixins.json",
    "vivecraft.alexmobs.mixins.json",
    "vivecraft.armourers_workshop.mixins.json",
    "vivecraft.bedrockify.mixins.json",
    "vivecraft.blur.mixins.json",
    "vivecraft.cataclysm.mixins.json",
    "vivecraft.dynamicfps.mixins.json",
    "vivecraft.elementa.mixins.json",
    "vivecraft.emf.mixins.json",
    "vivecraft.epicfight.mixins.json",
    "vivecraft.iris.mixins.json",
    "vivecraft.mca.mixins.json",
    "vivecraft.modefite.mixins.json",
    "vivecraft.optifine.mixins.json",
    "vivecraft.rei.mixins.json",
    "vivecraft.resolutioncontrol.mixins.json",
    "vivecraft.sereneseasons.mixins.json",
    "vivecraft.sodium.mixins.json",
    "vivecraft.trinkets.mixins.json",
    "vivecraft.voxy.mixins.json",
    "vivecraft.xaerosmimimap.mixins.json"
]

architectury {
    platformSetupLoomIde()
    forge()
}

loom {
    accessWidenerPath = project(":common").loom.accessWidenerPath

    forge {
        convertAccessWideners = true
        extraAccessWideners.add loom.accessWidenerPath.get().asFile.name

        for(String mixin : mixins) {
            mixinConfig(mixin)
        }
    }
}

configurations {
    common
    shadowCommon // Don't use shadow from the shadow plugin because we don't want IDEA to index this.
    bundle {
        // bundle command, to copy jar contents with the shadow plugin
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentForge.extendsFrom common
}


dependencies {
    forge "net.minecraftforge:forge:${rootProject.forge_version}"

    common(project(path: ":common", configuration: "namedElements")) { transitive false }
    shadowCommon(project(path: ":common", configuration: "transformProductionForge")) { transitive = false }

    // modCompileOnly("maven.modrinth:rubidium:0.6.5")
    // modCompileOnly("maven.modrinth:oculus:1.20-1.6.4")

    forgeRuntimeLibrary("org.lwjgl:lwjgl-openvr:${rootProject.lwjgl_version}") { transitive = false }
    forgeRuntimeLibrary("org.lwjgl:lwjgl-openvr:${rootProject.lwjgl_version}:natives-linux") { transitive = false }
    forgeRuntimeLibrary("org.lwjgl:lwjgl-openvr:${rootProject.lwjgl_version}:natives-macos") { transitive = false }
    forgeRuntimeLibrary("org.lwjgl:lwjgl-openvr:${rootProject.lwjgl_version}:natives-windows") { transitive = false }
    forgeRuntimeLibrary("com.illposed.osc:javaosc-core:0.9") { transitive = false }
    forgeRuntimeLibrary("com.github.bhaptics:tact-java:0.1.4") { transitive = false }
    forgeRuntimeLibrary("org.java-websocket:Java-WebSocket:1.5.1") { transitive = false }

    // shadow the natives
    bundle("org.lwjgl:lwjgl-openvr:${rootProject.lwjgl_version}") { transitive = false }
    bundle("org.lwjgl:lwjgl-openvr:${rootProject.lwjgl_version}:natives-linux") { transitive = false }
    bundle("org.lwjgl:lwjgl-openvr:${rootProject.lwjgl_version}:natives-macos") { transitive = false }
    bundle("org.lwjgl:lwjgl-openvr:${rootProject.lwjgl_version}:natives-windows") { transitive = false }

    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:${rootProject.mixin_extras_version}"))
    implementation(include("io.github.llamalad7:mixinextras-forge:${rootProject.mixin_extras_version}"))

    include(implementation("org.joml:joml:1.10.8"))

    include(implementation("com.illposed.osc:javaosc-core:0.9"))
    include(implementation("com.github.bhaptics:tact-java:0.1.4"))
    include(implementation("org.java-websocket:Java-WebSocket:1.5.1"))
}

shadowJar {
    exclude "fabric.mod.json"
    exclude "architectury.common.json"

    configurations = [
        project.configurations.shadowCommon,
        project.configurations.bundle
    ]
    archiveClassifier.set("dev-shadow")
}

remapJar {
    input.set shadowJar.archiveFile
    dependsOn shadowJar
    archiveClassifier.set('forge')
}

jar {
    archiveClassifier.set("dev")
    manifest {
        attributes(
            'Main-Class': "org.vivecraft.LaunchPopup"
        )
    }
}

sourcesJar {
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}
